Content-Type: text/enriched
Text-Width: 80

#+REVEAL_THEME: black
#+reveal_title_slide: nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_TRANS: linear
#+REVEAL_HLEVEL: 2
#+REVEAL_MARGIN: 0.1
#+OPTIONS: num:nil toc:nil date:nil reveal_title_slide:nil
#+REVEAL_EXTRA_CSS: ./css/theme/osu.css


<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_COMMENT
</x-color></x-bg-color>Title slide
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_COMMENT
</x-color></x-bg-color><x-color><param>#FD971F</param>* The development of shp2nosql: Command line tools for spatial data and NoSQL databases</x-color>

Matthew Haffner


Department of Geography


Oklahoma State University


<x-color><param>#66D9EF</param>[[https://mhaffner.github.io/presentations/shp2nosql.html]]</x-color>
<x-color><param>#FD971F</param>* Introduction</x-color>
- Motivation
  - Smoother NoSQL entry for geographers
  - Reproducibility
  - Collaboration and openness 
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_NOTES
</x-color></x-bg-color><x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_NOTES
</x-color></x-bg-color><x-color><param>#FD971F</param>* Package details</x-color>
- Requires shapefile as an input
- Inserts/indexes records into a database
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_NOTES
</x-color></x-bg-color>- Shapefile can come from census or local file
- Similar to shp2pgsql (and other similar tools)
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_NOTES
</x-color></x-bg-color><x-color><param>#FD971F</param>* Package details</x-color>
- Written in Bash (4.4)
- Relies on
  - <italic>/ogr2ogr (gdal)/</italic>
  - <italic>/getopts/</italic>
  - <italic>/Python/</italic>
- Works with

  - Elasticsearch
  - MongoDB
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_NOTES
</x-color></x-bg-color>Optional dependencies
- esbulk (multiprocessing utility written in go)
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_NOTES
</x-color></x-bg-color><x-color><param>#FD971F</param>* Package details</x-color>
- Works on GNU/Linux systems
- License: GNU General Public License v. 3
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_NOTES
</x-color></x-bg-color>- Tested on Arch Linux, Ubuntu, others?
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_NOTES
</x-color></x-bg-color><x-color><param>#FD971F</param>* Elasticsearch</x-color>
<x-color><param>#FD971F</param>* MongoDB</x-color>
<x-color><param>#FD971F</param>* Examples</x-color>
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_SRC shell 
</x-color></x-bg-color><x-color><param>#75715E</param><x-bg-color><param>#3E3D31</param><x-color><param>#F8F8F0</param># Elasticsearch
</x-color></x-bg-color></x-color><x-bg-color><param>#3E3D31</param><x-color><param>#F8F8F0</param>shp2nosql -R -d elasticsearch -f state -i us_states -t state 

<x-color><param>#75715E</param># an equivalent, more readable version with comments
</x-color>shp2nosql <x-color><param>#E6DB74</param>\</x-color>
-R <x-color><param>#AE81FF</param>`# remove the database if it exists`</x-color> <x-color><param>#E6DB74</param>\</x-color>
-d elasticsearch <x-color><param>#AE81FF</param>`# database type`</x-color> <x-color><param>#E6DB74</param>\</x-color>
-f state <x-color><param>#AE81FF</param>`# file to get from US Census TIGER files`</x-color> <x-color><param>#E6DB74</param>\</x-color>
-i us_states <x-color><param>#AE81FF</param>`# index name`</x-color> <x-color><param>#E6DB74</param>\</x-color>
-t state <x-color><param>#AE81FF</param>`# document type`</x-color>
</x-color></x-bg-color><x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_SRC
</x-color></x-bg-color><x-color><param>#FD971F</param>* Project goals</x-color>
<x-color><param>#FD971F</param>* Questions/future directions</x-color>
- How to deal with alternative SRS?
- Error reporting?
- More intuitive option flags?
- Installation?
- Other databases?
- Long term goals?
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+BEGIN_NOTES
</x-color></x-bg-color>- Publication outlets? Is this even publication worthy?
<x-bg-color><param>#35331D</param><x-color><param>#75715E</param>#+END_NOTES
</x-color></x-bg-color><x-color><param>#FD971F</param>* Conclusion</x-color>
- Software package: <x-color><param>#66D9EF</param>https://github.com/mhaffner/shp2nosql</x-color>
- Presentation: <x-color><param>#66D9EF</param>https://mhaffner.github.io/presentations/shp2nosql.html</x-color>
